package com.niftyengine.engine

import com.niftyengine.engine.core.Session
import com.niftyengine.engine.engines.HistoricalBacktest
import com.niftyengine.engine.engines.HistoricalChunk
import com.niftyengine.engine.engines.HistoricalDataSource
import com.niftyengine.engine.model.Candle
import com.niftyengine.engine.model.FuturesBar
import com.niftyengine.engine.model.Sector
import com.niftyengine.engine.sim.SimulatedMarket
import java.time.LocalDate
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertTrue

/** Minute history generated by the simulator, served through the same interface the Kite source implements. */
class SimHistory(days: Int, seed: Long = 9) : HistoricalDataSource {
    override val description = "simulator"
    val nifty = ArrayList<Candle>(); val vix = ArrayList<Candle>(); val bank = ArrayList<Candle>()
    val fut = ArrayList<FuturesBar>(); val stocks = HashMap<String, ArrayList<Candle>>(); val sectors = HashMap<Sector, ArrayList<Candle>>()
    val daily = ArrayList<Candle>()
    val dayList = ArrayList<LocalDate>()
    var maxBarTimeSeen = 0L

    init {
        val sim = SimulatedMarket(seed = seed, startDate = LocalDate.of(2026, 6, 1))
        var cur: LocalDate? = null
        repeat(days * (Session.SESSION_MINUTES - 1)) {
            val s = sim.collect(0)
            val d = Session.zdt(s.timestamp).toLocalDate()
            if (d != cur) { cur = d; dayList += d }
            val t = s.timestamp - 60_000L // bar that just completed
            fun c(x: Double) = Candle(t, x, x, x, x, 1.0)
            nifty += c(s.nifty.last); s.vix?.let { vix += c(it.last) }; s.bankNifty?.let { bank += c(it.last) }
            s.futures?.let { fut += FuturesBar(t, it.last, it.openInterest, 100.0) }
            s.constituents.forEach { (k, v) -> stocks.getOrPut(k) { ArrayList() } += c(v.last) }
            s.sectors.forEach { (k, v) -> sectors.getOrPut(k) { ArrayList() } += c(v.last) }
            if (daily.isEmpty()) daily += s.nifty.daily
        }
    }

    override fun tradingDays(from: LocalDate, to: LocalDate) = dayList.filter { it in from..to }
    override fun chunk(from: LocalDate, to: LocalDate): HistoricalChunk {
        val lo = Session.sessionStart(from.atStartOfDay(Session.IST).toInstant().toEpochMilli()) - 4 * 86_400_000L
        val hi = Session.closeOf(to) + 60_000L
        fun f(l: List<Candle>) = l.filter { it.t in lo..hi }
        return HistoricalChunk(f(nifty), f(vix), f(bank), fut.filter { it.t in lo..hi },
            sectors.mapValues { f(it.value) }, stocks.mapValues { f(it.value) }, stockBarMinutes = 1)
    }
    override fun dailyBefore(day: LocalDate) = daily.filter { it.t < Session.sessionStart(day.atStartOfDay(Session.IST).toInstant().toEpochMilli()) } to emptyList<Candle>()
}

class BacktestTest {
    @Test fun replaysHistoryWalkForwardWithBaselines() {
        val src = SimHistory(15)
        val bt = HistoricalBacktest(EngineConfig(), HistoricalBacktest.Config(chunkDays = 5, recalibrateEveryDays = 3, minCalibrationSamples = 60))
        val t0 = System.currentTimeMillis()
        val run = bt.run(src, src.dayList.first(), src.dayList.last())
        val r = run.report
        val ms = System.currentTimeMillis() - t0
        println("backtest: ${r.days} days, ${r.cycles} cycles, ${r.predictions} predictions in ${ms} ms (%.1f ms/cycle)".format(ms.toDouble() / r.cycles))
        r.baselines.forEach { println("  %-7s n=%d model acc %.2f · momentum acc %.2f · Brier %.3f vs climatology %.3f · skill %+.3f · in-range %.2f · rates %s"
            .format(it.horizon, it.n, it.modelAccuracy, it.momentumAccuracy, it.modelBrier, it.climatologyBrier, it.brierSkill, it.rangeHitRate, it.classRates.mapValues { v -> "%.2f".format(v.value) })) }
        r.thresholds.filter { it.horizon == "M30" && !it.calibrated }.forEach { println("  raw ≥%.2f → %d signals, hit %.2f, avg %+.1f pts".format(it.threshold, it.signals, it.hitRate, it.avgMovePts)) }
        println("  calibrated Brier (walk-forward) = %.3f over %d · ${r.calibration.note}".format(r.calibratedBrier, r.calibratedN))

        assertEquals(15, r.days)
        assertTrue(r.predictions >= 15 * 70, "≈74 five-minute steps per day")
        assertTrue(r.baselines.filter { it.horizon in listOf("M30", "M60", "M180", "CLOSE", "WEEKLY") }.all { it.n > 0 && !it.climatologyBrier.isNaN() },
            r.baselines.joinToString { "${it.horizon}=${it.n}" })
        assertTrue(run.records.any { rec -> rec.horizons.any { it.calibrated } }, "walk-forward calibration engaged after enough days")
        val firstDay = src.dayList.first()
        assertTrue(run.records.filter { Session.zdt(it.timestamp).toLocalDate() == firstDay }.none { rec -> rec.horizons.any { it.calibrated } }, "day 1 cannot use calibration")
        assertTrue(run.records.all { it.decision != "DATA_ERROR" }, "market-only mode must not trip on missing option chain")
        assertTrue(r.regimes.isNotEmpty())
    }
}
